spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.129:8848
    alicloud:
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
        appcode: 4a4ed7c64e5e408f81931044a16e169e
        method: POST


  application:
    name: gulimall-third-party
server:
  port: 12000